version: '3.9'
services:
  client-app:
    build: 
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client-app:/usr/src/client-app
      - /usr/src/client-app/node_modules
    tty: true
    links:
      - db
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d