version: '3.9'
services:
  client-app:
    build: 
      context: ./client-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./client-app:/usr/src/client-app
      - /usr/src/client-app/node_modules
    tty: true
    links:
      - db
  db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports: 
      - "3306:3306"
    volumes:
      - ./data/mysql/db:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d