version: '3.9'
services:
  client-app:
    build: ./client-app
    ports:
      - "8080:8080"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./client-app:/usr/src/client-app
      - /usr/src/client-app/node_modules
    tty: true