version: '3.9'

services:
  nginx-server:
    build: ./nginx
    volumes:
      - ./nginx/dist:/usr/share/nginx/html
    ports:
      - "8080:8080"
      - "443:443"
  client-app:
    build: ./client-app
    ports:
      - "4200:4200"
    volumes:
      - ./client-app:/usr/src/client-app
      - /usr/src/client-app/node_modules
    tty: true
  fastapi:
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    ports:
      - "8000:8000"